# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fab59553fbbcb98e94ed91416adae47f1c9df5128fffece93e9c576330259ab9e1cc0d442dba5c470ed402ace489da5d4722aea66aeba69257830405f61e6b76

test:
  secret_key_base: b5b6a976faf481d13822fa8f77fbd737e2955ac9962a616633efc70e76274c393c475a9c6deffe91461115bd25ff8c19435d81dc91181d1e289f7eb952a3211f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
